"""init schema

Revision ID: 83fd9806c3c5
Revises: 
Create Date: 2026-02-18 19:05:16.707395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83fd9806c3c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('MAIN', 'STORE', name='accounttype'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_fact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('store_name', sa.String(length=128), nullable=True),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('product_name_snapshot', sa.Text(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('invoice', sa.String(length=128), nullable=True),
    sa.Column('return_type', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sale_date', 'application_id', 'sku', 'price', 'total', 'invoice', 'return_type', name='uq_sales_fact_group')
    )
    op.create_table('sku_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MISSING', 'DELETED', 'UNKNOWN', name='skustatus'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_title', sa.Text(), nullable=True),
    sa.Column('resolved_offer_id', sa.String(length=64), nullable=True),
    sa.Column('resolved_item_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'sku', name='uq_store_sku')
    )
    op.create_table('stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_sales_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_run_id', sa.Integer(), nullable=False),
    sa.Column('source_row_no', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('client', sa.String(length=256), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('marking', sa.String(length=64), nullable=True),
    sa.Column('store_name', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('district', sa.String(length=128), nullable=True),
    sa.Column('inn', sa.String(length=32), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('first_payment_date', sa.String(length=64), nullable=True),
    sa.Column('approval_date', sa.String(length=64), nullable=True),
    sa.Column('partner_name', sa.String(length=256), nullable=True),
    sa.Column('invoice', sa.String(length=128), nullable=True),
    sa.Column('return_type', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_run_id'], ['report_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_run_id', 'source_row_no', name='uq_raw_report_row')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_sales_rows')
    op.drop_table('stores')
    op.drop_table('sku_registry')
    op.drop_table('sales_fact')
    op.drop_table('report_runs')
    op.drop_table('merchant_accounts')
    # ### end Alembic commands ###
